name       : clinfo
version    : 3.0.23.01.25
release    : 9
source     :
    - https://github.com/Oblomov/clinfo/archive/refs/tags/3.0.23.01.25.tar.gz : 6dcdada6c115873db78c7ffc62b9fc1ee7a2d08854a3bccea396df312e7331e3
license    : CC0-1.0
component  : programming.tools
homepage   : https://github.com/Oblomov/clinfo/
summary    : Tool that enumerates all system OpenCL platform and device properties
description: |
    A simple OpenCL application that enumerates all possible platform and device properties on the system. Inspired by AMD's program of the same name, it is coded in pure C99 and it tries to output all possible information, including that provided by platform-specific extensions, and not to crash on platform-unsupported properties (e.g. 1.2 properties on 1.1 platforms).
builddeps  :
    - pkgconfig(OpenCL)
build      : |
    %make
install    : |
    install -Dm 00755 clinfo $installdir/usr/bin/clinfo
    install -Dm 00644 man1/clinfo.1 $installdir/usr/share/man/man1/clinfo.1
