name       : clinfo
version    : 2.2.18.03.22
release    : 4
source     :
    - https://github.com/Oblomov/clinfo/archive/2.2.18.03.22.tar.gz : b7651f483c7dee95238b9299b85d254500e7514c8e4acceb4b0db002ba598347
license    : CC0-1.0
component  : system.utils
summary    : A simple OpenCL application that enumerates all possible platform and device properties
description: |
    A simple OpenCL application that enumerates all possible platform and device properties. Inspired by AMD's program of the same name, it is coded in pure C99 and it tries to output all possible information, including that provided by platform-specific extensions, and not to crash on platform-unsupported properties (e.g. 1.2 properties on 1.1 platforms).
builddeps  :
    - pkgconfig(OpenCL)
rundeps    :
    - beignet
build      : |
    %make
install    : |
    install -D -m 00755 clinfo $installdir/usr/bin/clinfo
    install -D -m 00644 man1/clinfo.1 $installdir/usr/share/man/man1/clinfo.1
