name       : clinfo
version    : 2.1.16.01.12
release    : 1
source     :
    - https://github.com/Oblomov/clinfo/archive/2.1.16.01.12.tar.gz : f92fc60f337ad86c8506d7d03358bf47980cb08fca1a0ca496b15282db59dea3
license    : Public-Domain
component  : system.utils
summary    : A simple OpenCL application that enumerates all possible platform and device properties.
description: |
    A simple OpenCL application that enumerates all possible platform and device properties.
builddeps  :
    - pkgconfig(OpenCL)
    - beignet-devel
build      : |
    %make
install    : |
    install -D -m 00755 clinfo $installdir/usr/bin/clinfo
    install -D -m 00644 man/clinfo.1 $installdir/usr/share/man/man1/clinfo.1
