name       : clinfo
version    : 2.2.17.10.25
release    : 3
source     :
    - https://github.com/Oblomov/clinfo/archive/2.2.17.10.25.tar.gz : 23cab774915eea6730582abfc449ac57dc10f2ce7b39293e56166ed500383862
license    : CC0-1.0
component  : system.utils
summary    : A simple OpenCL application that enumerates all possible platform and device properties
description: |
    A simple OpenCL application that enumerates all possible platform and
    device properties. Inspired by AMD's program of the same name, it is
    coded in pure C99 and it tries to output all possible information,
    including that provided by platform-specific extensions, and not to
    crash on platform-unsupported properties (e.g. 1.2 properties on 1.1
    platforms).
builddeps  :
    - pkgconfig(OpenCL)
    - beignet-devel
build      : |
    %make
install    : |
    install -D -m 00755 clinfo $installdir/usr/bin/clinfo
    install -D -m 00644 man1/clinfo.1 $installdir/usr/share/man/man1/clinfo.1
